artifact_uri: file:///C:/Users/shahu/Documents/OneDrive/OPEN%20CLASSROOMS/PROJET%206/Scoring_Model/mlruns/733106191722119945/786c01cf5ecc4958b54afa6f07b20b2b/artifacts
end_time: 1765201476362
entry_point_name: ''
experiment_id: '733106191722119945'
lifecycle_stage: active
run_id: 786c01cf5ecc4958b54afa6f07b20b2b
run_name: test_model_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1765201462046
status: 3
tags: []
user_id: shahu
