artifact_uri: file:///C:/Users/shahu/Documents/OneDrive/OPEN%20CLASSROOMS/PROJET%206/Scoring_Model/mlruns/733106191722119945/0d857db44c8947a8815ad8e50489daff/artifacts
end_time: 1765273283162
entry_point_name: ''
experiment_id: '733106191722119945'
lifecycle_stage: active
run_id: 0d857db44c8947a8815ad8e50489daff
run_name: test_model_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1765273274568
status: 3
tags: []
user_id: shahu
