artifact_uri: file:///C:/Users/shahu/Documents/OneDrive/OPEN%20CLASSROOMS/PROJET%206/Scoring_Model/mlruns/733106191722119945/d55a07acfc1344b4983d3317a2bab09a/artifacts
end_time: 1765365853069
entry_point_name: ''
experiment_id: '733106191722119945'
lifecycle_stage: active
run_id: d55a07acfc1344b4983d3317a2bab09a
run_name: test_model_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1765365827203
status: 3
tags: []
user_id: shahu
